"""Initial migration

Revision ID: 35e824538476
Revises: 
Create Date: 2025-05-01 16:00:41.200446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35e824538476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_credits', sa.Integer(), nullable=False))

    with op.batch_alter_table('teaching', schema=None) as batch_op:
        batch_op.alter_column('professor_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('schedule_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_constraint('teaching_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('teaching_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'schedule', ['schedule_id'], ['schedule_id'])
        batch_op.create_foreign_key(None, 'professor', ['professor_id'], ['professor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teaching_ibfk_2', 'schedule', ['schedule_id'], ['schedule_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('teaching_ibfk_1', 'professor', ['professor_id'], ['professor_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('schedule_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('professor_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('total_credits')

    # ### end Alembic commands ###
